# language: python
#
# script:
#   - python -m pytest -v


language: python
python:
- '3.8'
services:
- postgresql
addons:
  postgresql: '9.6'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database hireup_test;' -U postgres
- python manage.py db upgrade
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure:
  app: hireup-be
  on:
    repo: HireUp-Turing/HireUp_backend
    branch: main
  skip_cleanup: 'true'
  run:
    - pip install -r requirements.txt
    - python manage.py db upgrade
