language: python
python:
  - '3.7.3'
install:
  - pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database hireup_test;' -U postgres
- python manage.py db upgrade
script:
  - pytest
