"""empty message

Revision ID: 4b3e69726f08
Revises: 0dac9dc5d3a7
Create Date: 2020-10-26 21:30:51.053142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3e69726f08'
down_revision = '0dac9dc5d3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('bio', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'bio')
    # ### end Alembic commands ###
