"""empty message

Revision ID: 8fb74fa0d971
Revises: 0dac9dc5d3a7
Create Date: 2020-10-26 21:42:31.034491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb74fa0d971'
down_revision = '0dac9dc5d3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('bio', sa.String(length=250), nullable=True))
    op.add_column('applicants', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'username')
    op.drop_column('applicants', 'bio')
    # ### end Alembic commands ###
